export {
  ProvenanceStatus,
  Zone,
  type EntryType,
  type ResolutionStatus,
  type Provenance,
  type KnowledgeEntry,
  type FactEntry,
  type DecisionEntry,
  type GotchaEntry,
  type PatternEntry,
  type LinkEntry,
  type TombstoneEntry,
  type AreaMetadata,
  type ManifestArea,
  type ManifestFile,
  type EntryFilter,
  type AddEntryOptions,
  type AddFactOptions,
  type AddDecisionOptions,
  type AddGotchaOptions,
  type AddPatternOptions,
  type AddLinkOptions,
  type KnowledgeStore,
  type SearchEngine,
} from './types.js';
